site_name: MkDocs Quiz Plugin Example
site_description: Example documentation demonstrating the MkDocs Quiz Plugin
site_author: MkDocs Quiz Plugin Team

# Repository
repo_name: mkdocs-quiz
repo_url: https://github.com/macielcalebe/mkdocs-quiz/example

# Theme configuration
theme:
  name: material

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html

# Plugins
plugins:
  - search
  - mkdocs_quiz # HERE WE HAVE THE PLUGIN!

# Navigation
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Quiz Examples:
    - Multiple Choice: examples/multiple-choice.md
    - Text Input: examples/text-input.md
    - Self Assessment: examples/self-assessment.md
    - Mixed Exercise: examples/mixed-exercise.md
  - Advanced Features: advanced.md
  - Troubleshooting: troubleshooting.md

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/macielcalebe/mkdocs-quiz/example
